### ISSUE TITLE
使用bianPush插件时报错cannot import name 'spot' from 'binance'

### ISSUE THREAD

**Issue by IsaacTheMouse** [scofieldle/LeoBot#1]
binance版本0.3

**Comment by scofieldle** [comment]
我这边windows和ubuntu系统上装的binance都没有问题。建议自查下安装位置和安装时是否使用了sudo等命令，可以试试直接import binance报不报错

**Comment by sion934** [comment]
“pip install binance-connector”可以解决这个问题 @IsaacTheMouse
