### ISSUE TITLE
关于pixiv_new的问题

### ISSUE THREAD

**Issue by as6296463** [scofieldle/LeoBot#3]
如图，配置好refresh_token后运行出现如下错误，不知道如何解决，搞了一下午也没成果，只能求助大佬了
![QQ截图20211102165601](https://user-images.githubusercontent.com/37761817/139816224-00627c98-ce8f-4bfa-a94c-363f603de402.png)
。

**Comment by scofieldle** [comment]
这个是被风控了吧
